export const GUESS_LETTER = 'GUESS_LETTER';
export const CORRECT_GUESS = 'CORRECT_GUESS';
export const INCORRECT_GUESS = 'INCORRECT_GUESS';
export const REPEAT_GUESS = 'REPEAT_GUESS';
export const RESET_GUESSES = 'RESET_GUESSES';

export const GUESS_ACTIONS = new Set([
  GUESS_LETTER,
  CORRECT_GUESS,
  INCORRECT_GUESS,
  REPEAT_GUESS, RESET_GUESSES, ]);

export const RESET_REMAINING = 'RESET_REMAINING';
export const INCREMENT_REMAINING = 'INCREMENT_REMAINING';
export const DECREMENT_REMAINING = 'DECREMENT_REMAINING';

export const REMAINING_ACTIONS =
  new Set([ RESET_REMAINING, INCREMENT_REMAINING, DECREMENT_REMAINING, ]);
